apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: 160487/multi-client
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
              ephemeral-storage: "500Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"