name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t 160487/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true 160487/react-test npm test

      - name: Set Service Key
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
      
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: multi-k8s
      
      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker
      
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v3
        with:
          cluster_name: multi-k8s
          location: us-central1
      
      - name: Build
        run: |-
          docker build -t 160487/multi-client-k8s-gh:latest -t 160487/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t 160487/multi-server-k8s-gh:latest -t 160487/multi-server-k8s-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t 160487/multi-worker-k8s-gh:latest -t 160487/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push 160487/multi-client-k8s-gh:latest
          docker push 160487/multi-server-k8s-gh:latest
          docker push 160487/multi-worker-k8s-gh:latest
          
          docker push 160487/multi-client-k8s-gh:${{ env.SHA }}
          docker push 160487/multi-server-k8s-gh:${{ env.SHA }}
          docker push 160487/multi-worker-k8s-gh:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/client-deployment client=160487/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/server-deployment server=160487/multi-server-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=160487/multi-worker-k8s-gh:${{ env.SHA }}